# traefik.yml - minimal working config

ping:
  entryPoint: web

providers:
  docker:
    exposedByDefault: false
    network: headscale-net

certificatesResolvers:
  le:
    acme:
      email: denisreactfe@gmail.com     # твой email для Let's Encrypt
      storage: /acme.json
      httpChallenge:
        entryPoint: web

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: le
